menu:
  首页: / #需要hexo new page index,在index/index.md填写的内容将会展现在首页上
  文章: /list/ # 需要hexo new page list
  # 添加其他页面格式举例：
  # 关于: /about/ # 需要hexo new page about
  # 标签: /tags/ #需要hexo new page tags
  # 分类: /categories/ # 需要hexo new page categories
  # ...

# menu 中的哪些页面显示在首页中（“首页”必定显示）
showInMenu:
  #- 首页
  #- 文章

# 首页的页眉页脚
index:
  header: ㄅㄆㄇㄈㄉㄊㄋㄌㄍㄎㄏ
  #footer: Email:mailto:123456@qq.com # 除了可以填写任何文字外，可以自动邮箱链接化，但需按照这个格式填写：Email:xxx@gmail.com

# 联系方式 更多图标：https://remixicon.com/
contact:
  Github:
    - https://github.com/llsccm
    - ri-github-line
  Email:
    - mailto:p8203@qq.com
    - ri-mail-line

# 底部的链接自定义
footerLink:
  info: © 2023 # info这个单词不能修改，不想使用可为空
  # 添加链接格式 举例
  # 友链: /friends/ # 需要hexo new page friends
  # 联系: /contact/ # 需要hexo new page contact
  # 支持: /support/ # 需要hexo new page support
  # ...

# 除首页之外页面
post:
  footer: ㄅㄆㄇㄈㄉㄊㄋㄌㄍㄎㄏ # 底部左侧 自定义信息
  themeInfo: true # true | false # 是否开启 底部右侧 声明本站信息

# 相对于source目录下的头像url
favicon: /img/favicon.ico
# ---------------------------------------------------------------------------------------
# Comment plugin
# ---------------------------------------------------------------------------------------
comment:
  enable: false
  use: waline # values: waline

  # Waline
  # See: https://waline.js.org/guide/get-started.html
  waline:
    serverUrl: # Waline server url(vercel) example: https://example.example.com
    lang: zh-CN # Waline language, default: zh-CN. See: https://waline.js.org/guide/client/i18n.html

# 你可能会用到的帖子 https://ninojay.top/2023/website-cdn/
cdn:
  enable: false # 如果你修改了css/js等静态文件，请关闭cdn
  choose: jsdelivr # jsdelivr | unpkg | aliyun     # 都调整为利于国内的cdn，建议使用jsdelivr, 对速度还是不满意可选 aliyun

version: v1.6.6
